### ISSUE TITLE
Container does not start because of `java.lang.IllegalStateException: No configuration store implementations found on the classpath`

### ISSUE THREAD

**Issue by heubeck** [heubeck/statuspage-prometheus-exporter#1]
```
 ~/w/g/h/statuspage-prometheus-exporter    podman run -v /home/heubeck/w/github/heubeck/statuspage-prometheus-exporter:/config -e STATUS_CONFIG_FILE=/config/config.yaml -ti quay.io/heubeck/statuspage-prometheus
-exporter:0.0.1
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-07-16 13:46:02,599 WARN  [io.qua.application] (main) Setting the 'javax.net.ssl.trustStore' system property will not have any effect at runtime. Make sure to set this property at build time (for example by setting 'quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=someValue').
2020-07-16 13:46:02,620 INFO  [io.quarkus] (main) status-metrics-exporter 0.0.1 native (powered by Quarkus 1.6.0.Final) started in 0.020s. Listening on: http://0.0.0.0:8080
2020-07-16 13:46:02,620 INFO  [io.quarkus] (main) Profile prod activated.
2020-07-16 13:46:02,620 INFO  [io.quarkus] (main) Installed features: [cdi, kotlin, mutiny, scheduler, smallrye-context-propagation, vertx, vertx-web]
2020-07-16 13:46:03,006 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=1_p1nkun1c0rns.statusmetrics.Status_ScheduledInvoker_fetchStatus_8b5b01eda7f4933a86669442115dc3b720600651, interval=30000]: java.lang.IllegalStateException: No configuration store implementations found on the classpath
        at io.vertx.config.impl.ConfigRetrieverImpl.<init>(ConfigRetrieverImpl.java:74)
        at io.vertx.config.ConfigRetriever.create(ConfigRetriever.java:53)
        at p1nkun1c0rns.statusmetrics.Config.<init>(Config.kt:21)
        at p1nkun1c0rns.statusmetrics.Config_Bean.create(Config_Bean.zig:279)
        at p1nkun1c0rns.statusmetrics.Config_Bean.create(Config_Bean.zig:294)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:88)
        at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
        at p1nkun1c0rns.statusmetrics.Config_ClientProxy.arc$delegate(Config_ClientProxy.zig:92)
        at p1nkun1c0rns.statusmetrics.Config_ClientProxy.getConfig(Config_ClientProxy.zig:181)
        at p1nkun1c0rns.statusmetrics.Status.fetchStatus(Status.kt:23)
        at p1nkun1c0rns.statusmetrics.Status_ClientProxy.fetchStatus(Status_ClientProxy.zig:270)
        at p1nkun1c0rns.statusmetrics.Status_ScheduledInvoker_fetchStatus_8b5b01eda7f4933a86669442115dc3b720600651.invokeBean(Status_ScheduledInvoker_fetchStatus_8b5b01eda7f4933a86669442115dc3b720600651.zig:45)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:130)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

^C2020-07-16 13:46:11,338 INFO  [io.quarkus] (main) status-metrics-exporter stopped in 0.006s

```

**Comment by heubeck** [comment]
Switched from vertx config to ordinary file access, no problems anymore
